### ISSUE TITLE
No commander spawning.

### ISSUE THREAD

**Issue by Ebolavector** [SmalkiGroove/mcp-mod#2]
Hi ! I have a bug with your awesome mod, i have SCFA on steam and GOG and with the two licenses i have no commander spawning on the start of all games, i cannot play... Could you fixe this issue ? Thx

**Comment by SmalkiGroove** [comment]
Hello, I've fixed it already. You can find the download link on moddb :)

**Comment by Ebolavector** [comment]
I've download it and yes it work "partially". On FAF it launch normaly but without special units like Field engineers and on GOG version i have no commander spawning. (J'ai cru comprendre sur MODDB que vous êtes français, si tel est le cas ça pourrait être plus simple pour en parler ?^^)

**Comment by Zzwzzzz** [comment]
Mod on Moddb was deleted for some reason. I download mod from here as installation guide says, but...commander still doesn't spawns. Actually it spawn, but no resources, no model, just walking nothing that have unlocked everything for building, but doesn't build that. Also icons is broken (circle named "Place Holder"). Even cheat menu doesn't helps: Commander with model doesn't have animations, still doesn't build and produce resources, engineers doesn't helps too. Units, spawned by cheat menu, can't shoot and doesn't have animation too.

**Comment by SmalkiGroove** [comment]
Damn... after all the time I've spent doing the articles and screenshots...
I need to make a better guide here on Github but right now I don't have time, expect this by the end of the year.

@Ebolavector Oui, sur FAF tu n'as aucune unité du mod ? Tu peux lancer une game faire F9 et me montrer ? Pour la version Steam (je suppose que GOG c'est pareil) j'avais sorti une autre version sur moddb mais comme mon mod a été supprimé j'espère que tu l'avais téléchargée avant sinon tu vas devoir attendre que je fasse toute la présentation, mise en page, guides sur Github d'ici la fin de l'année.

**Comment by Ebolavector** [comment]
@SmalkiGroove C'est bon sur FAF !!! Impeccable , par contre sur la version Steam et surtout la GOG la version que tu avais proposé pour moi a toujours le même problème de commander, je suis désolé qu'après tout ce que tu avais fait je n'ai pas réussi à le faire fonctionner sur la version GOG ! ^^' Mais vraiment ton mod est génial et ça n'en change pas la qualité, c'est juste que quand j'organise des LAN j'aimerais beaucoup y jouer avec mes potes sur la version que mes potes et moi possédons (la GOG). Prend ton temps en tout cas, et merci pour ton boulot sur ce mod ! ;)

**Comment by SmalkiGroove** [comment]
@Ebolavector merci ça fait plaisir :) quand j'aurai réglé les problèmes je te tagerai

**Comment by Ebolavector** [comment]
@SmalkiGroove Salut ! Je viens de voir que tu as fait une maj, as-tu eu le temps de voir pour les soucis sur ma version du jeu ?
Maintenant les commanders apparaissent mais l'ia ne bouge pas.

**Comment by SmalkiGroove** [comment]
@Ebolavector Salut, je vais avoir besoin de toi pour résoudre les bugs sur la version GOG du coup. Ajoute moi sur Discord RachidSystem#1987

**Comment by Ebolavector** [comment]
> @Ebolavector Salut, je vais avoir besoin de toi pour résoudre les bugs sur la version GOG du coup. Ajoute moi sur Discord RachidSystem#1987

ça marche je t'ajoute, c'est moi Renardpolaire
